apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-16T18:44:57Z"
  name: carts-canary
  resourceVersion: "89438"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 0d349c0e-f045-11e9-aaf5-42010a8001a2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
